apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
  namespace: default
spec:
  cassandra:
    serverVersion: "5.0.8"
    datacenters:
      - metadata:
          name: dc1
        size: 3
        softPodAntiAffinity: true
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: ebs-gp3
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        resources:
          requests:
            cpu: "4"
            memory: "3Gi"
          limits:
            cpu: "6"
            memory: "6Gi"
        config:
          jvmOptions:
            heapSize: 2G
